services:
  app:
    image: registry.cn-shenzhen.aliyuncs.com/public-8ikbycng7s/any-auto-register:d368dae
    container_name: ${CONTAINER_NAME:-any-auto-register}
    init: true
    restart: unless-stopped
    env_file:
      - 1panel.env
    environment:
      HOST: 0.0.0.0
      PORT: "8000"
      APP_RELOAD: "0"
      APP_CONDA_ENV: docker
      APP_RUNTIME_DIR: /runtime
      APP_ENABLE_SOLVER: ${APP_ENABLE_SOLVER:-1}
      SOLVER_PORT: "8889"
      SOLVER_BIND_HOST: 0.0.0.0
      LOCAL_SOLVER_URL: http://127.0.0.1:8889
      SOLVER_BROWSER_TYPE: ${SOLVER_BROWSER_TYPE:-camoufox}
      PLAYWRIGHT_HEADLESS: ${PLAYWRIGHT_HEADLESS:-}
    ports:
      - "${APP_PORT:-8000}:8000"
      - "${SOLVER_PORT_HOST:-8889}:8889"
      - "${CLIPROXYAPI_PORT:-8317}:8317"
      - "${GROK2API_PORT:-8011}:8011"
    volumes:
      - ${APP_RUNTIME_BIND:-./data}:/runtime
      - ${APP_EXT_TARGETS_BIND:-./_ext_targets}:/_ext_targets
      - ${APP_EXTERNAL_LOGS_BIND:-./external_logs}:/app/services/external_logs
    shm_size: "1gb"
    networks:
      - 1panel-network

networks:
  1panel-network:
    external: true
